"""add contact id

Revision ID: 86698672d19c
Revises: 8ac1b86fccfa
Create Date: 2025-03-21 13:28:49.121034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86698672d19c'
down_revision = '8ac1b86fccfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('contact_id')

    # ### end Alembic commands ###
